# Generated by Django 5.2.8 on 2025-11-11 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.PositiveIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), ('Нормально', 3), ('Хорошо', 4), ('Отлично', 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
