# Generated by Django 5.2.8 on 2025-11-11 20:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Roman', 'Роман'), ('Fantasy', 'Фантастика'), ('Detective', 'Детектив'), ('Fiction', 'Художественная литература'), ('Fairy tale', 'Сказка'), ('hycology', 'Психология'), ('Education', 'Образование')], default='Не указано', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(upload_to='file/book/%y/%m', verbose_name='Книга электронная'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/book/%y/%m', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.PositiveIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
