# Generated by Django 5.2.8 on 2025-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book_price_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(blank=True, choices=[('KGS', 'сом'), ('USD', '$'), ('RUB', '₽'), ('EUR', '€'), ('KZT', '₸')], max_length=10, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
